services:
  dev-app:
    build:
      context: .
    ports:
      - 5170:5173
    develop:
      watch:
        - action: rebuild
          path: .
  app:
    image: localhost/image-name
    ports:
      - 80:80
      - 443:443
