/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

export * as goldTokenSol from './GoldToken.sol';
export * as stringUtilsLibrarySol from './StringUtils.library.sol';
export { MysteryChineseChess__factory } from './MysteryChineseChess__factory';
