/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from '../../common';

export interface StringUtilsInterface extends Interface {
  getFunction(nameOrSignature: 'isBlank' | 'isUTF8Character' | 'length'): FunctionFragment;

  encodeFunctionData(functionFragment: 'isBlank', values: [string]): string;
  encodeFunctionData(functionFragment: 'isUTF8Character', values: [string]): string;
  encodeFunctionData(functionFragment: 'length', values: [string]): string;

  decodeFunctionResult(functionFragment: 'isBlank', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'isUTF8Character', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'length', data: BytesLike): Result;
}

export interface StringUtils extends BaseContract {
  connect(runner?: ContractRunner | null): StringUtils;
  waitForDeployment(): Promise<this>;

  interface: StringUtilsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  isBlank: TypedContractMethod<[str: string], [boolean], 'view'>;

  isUTF8Character: TypedContractMethod<[char: string], [boolean], 'view'>;

  length: TypedContractMethod<[str: string], [bigint], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'isBlank'): TypedContractMethod<[str: string], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'isUTF8Character'
  ): TypedContractMethod<[char: string], [boolean], 'view'>;
  getFunction(nameOrSignature: 'length'): TypedContractMethod<[str: string], [bigint], 'view'>;

  filters: {};
}
