/* Autogenerated file. Do not edit manually. */
/* tslint:disable */

import type * as goldTokenSol from './GoldToken.sol';
export type { goldTokenSol };
import type * as stringUtilsLibrarySol from './StringUtils.library.sol';
export type { stringUtilsLibrarySol };
export type { MysteryChineseChess } from './MysteryChineseChess';
